// Frontend/Angular/Angular-Crash-ToDoList/src/app/components/Pages/about/about.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {  }

}

<div>
  <h1>About</h1>
  <p>This is the To Do List app v1.0.0. It's part of the Angular Crash Course</p>
</div>

// Frontend/React/crash-to-do/src/components/pages/About.js
import React, {Component} from 'react';

class About extends Component {
    render() {
        return (
            <div>
                <h1>About</h1>
                <p>This is the To Do List App v1.0.0. It's part of a React Crash Course</p>
            </div>
        );
    };
}

export default About;
